POST  http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "redpanda",
  "name": "wasim",
  "password": "s3cr3t"
}

###

POST  http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "elgato",
  "name": "hazo",
  "password": "c0d3w0rd"
}

###

POST  http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "abcd",
  "password": "123"
}