POST  http://localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "express js router",
  "author": "strongloop",
  "url": "http://expressjs.com/en/api.html#router",
  "likes": 100,
  "user": "6389f7954a67a4c6ad56af4a"
}