POST  http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZHBhbmRhIiwiaWQiOiI2MzhiYmRhYjJiYWIwYzM4ZTFkZDA3NjciLCJpYXQiOjE2NzAxMDI0NTJ9.0KBKExHwYRUvl74slhqNZzH8uEDLOslTHTmyotRyPN4

{
  "title": "learn modern PHP",
  "author": "odan",
  "url": "https://odan.github.io/learn-php/",
  "likes": 826
}